На проверку
TinaevNK/js-part-0 pull request #1
Opened 2022-12-09 20:32 UTC by TinaevNK

# Домашнее задание по JS, часть первая

## Добавлены **функции**:
1. Сравнения двух объектов;
2. Получения стандартного типа (typeof);
3. Получения стандартных типов в итерируемой сущности (массив/список);
4. Проверки, чтобы все стандартные типы в списке были одинаковыми;
5. Получения реального типа;
6. Получения реальных типов в списке;
7. Проверки, чтобы все типы в списки были уникальными;
8. Получения реальных типов (с их количеством) из списка, с сортировкой по имени типа в лексикографическом порядке.

---

## Добавлено пару кастомных тестов для проверки функциональности.

---

Все тесты пройдены

### getType

  ```
[OK] Boolean
  
  [OK] Number
  
  [OK] String
  
  [OK] Array
  
  [OK] Object
  
  [OK] Function
  
  [OK] Undefined
  
  [OK] Null
```
  
### allItemsHaveTheSameType

  ```
[OK] All values are numbers
  
  [OK] All values are strings
  
  [OK] All values are strings but wait
  
  [OK] Values like a number
  
  [OK] Values like an object
```
  
### getTypesOfItems VS getRealTypesOfItems

  ```
[OK] Check basic types
  
  [OK] Check real types
```
  
### everyItemHasAUniqueRealType

  ```
[OK] All value types in the array are unique
  
  [OK] Two values have the same type
  
  [OK] There are no repeated types in knownTypes
```
  
### countRealTypes

  ```
[OK] Count unique types of array items
  
  [OK] Counted unique types are sorted
  
  [OK] Custom test by TinaevNK
```

2022-12-15 10:23 UTC, ipetropolsky requested changes
В `yarn.lock` странный дифф, как ты его получил? С таким нужно разобраться. Ты запушишь в мастер, я подтяну твои изменения, сделаю `yarn`, и всё опять поменяется. Так и будем гонять этот большой дифф. Дёшево и сердито — просто не коммитить его, если ты не менял пакеты. Но лучше понять, что не так.

2022-12-15 10:23 UTC, ipetropolsky commented on index.js
> +        for (let i = 0; i < a.length; i++) {
Может и тут `every`?

2022-12-15 10:23 UTC, ipetropolsky commented on index.js
> +    if (a instanceof Array && b instanceof Array) {
Вряд ли когда-то столкнёшься, но просто на заметку: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray#instanceof_vs_array.isarray

2022-12-15 10:23 UTC, ipetropolsky commented on index.js
> +    } else if (!Number.isFinite(value) && typeof value === 'number') {
Да можно было явно сравнить с +-Infinity. Так тоже ok.

2022-12-15 10:23 UTC, ipetropolsky commented on index.js
> +    return Object.prototype.toString.call(value).slice(8, -1).toLowerCase();
Есть типы из двух слов, будет не очень красиво после `toLowerCase`

2022-12-15 10:23 UTC, ipetropolsky commented on index.js
> +        const type = getRealType(item);
`getRealTypesOfItems`?

2022-12-15 10:23 UTC, ipetropolsky commented on index.js
> +    return set.size === arr.length;
👍

2022-12-15 10:23 UTC, ipetropolsky commented on index.js
> +        acc[getRealType(item)] ? acc[getRealType(item)]++ : (acc[getRealType(item)] = 1);
Что-то много вызовов одного и того же. Хоть там и семечки, давай всё же лишний раз не вызывать `getRealType`, тем более что это вопрос одной дополнительной строчки.

2022-12-15 10:23 UTC, ipetropolsky commented on index.js
> +    return Object.entries(map).sort();
Я тут ничего не вижу про сортировку массива из массивов: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort
Можно предположить, что это работает, потому что каждый подмассив приводится к строке, и у неё в начале оказывается ключ, по которому мы и сортируем. Но давай лучше явно укажем функцию сортировки, чтобы потом не гадать, что тут за магия.

2022-12-15 10:23 UTC, ipetropolsky commented on index.js
> +    'bigint',
Найдёшь ещё парочку?

2022-12-15 10:23 UTC, ipetropolsky commented on index.js
> +test('Custom test by TinaevNK', countRealTypes([{}, true, 'lost', {}, new Set(), [4, 8, 15, 16, 23, 42], new Date()]), [
В сообщении лучше написать, что проверяется, или смысл теста. И, кстати, в чём отличие этого теста от такого же выше? Просто так не надо плодить, это же время на поддержку и исправление при рефакторинге, и когда их много, просто долго ждать прохождения.

2022-12-15 10:23 UTC, ipetropolsky commented on package.json
> +    "postinstall": "ln -sf ../../githooks .git/hooks"
Выглядит очень странно. Почему тебе пришлось подняться на два уровня, если githooks лежит тут же? 🤔 А что не так с `pwd`?

2022-12-16 09:01 UTC, TinaevNK commented
> Скорее всего это получилось потому что пытался использовать оба пакетных менеджеров. Сейчас удалил package-lock и заменил yarn.lock на твой файл из репозитория.

2022-12-20 21:53 UTC, ipetropolsky commented on index.js
> +        return a.length === b.length && a.flat().every((el, i) => el === b.flat()[i]);
Не ну `flat` лишний, зачем. Это же разные массивы `[11, 12, 13]` и `[11, [12, 13]]`

2022-12-20 21:53 UTC, ipetropolsky commented on index.js
> +        acc[realType] ? acc[realType]++ : (acc[realType] = 1);
Внутри тернарника не очень хорошо делать присвоения, их там плохо видно, легко ошибиться, трудно потом найти где. Лучше так: `acc[realType] = (acc[realType] || 0) + 1`.

2022-12-20 21:53 UTC, ipetropolsky commented on index.js
> +            .reduce((acc, key) => {
Перекладыванием в объект ты ломаешь сортировку, потому что там она не гарантирована ) Тут можно прямо в reduce вместо объекта собрать массив, и будет гуд.

2022-12-26 02:12 UTC, ipetropolsky approved these changes

2023-01-04 15:15 UTC, merged